fix updateStartupScript in node v0.12.x
Buffer.indexOf() doesn't exist in old Node.js, so read the file into a
string instead.

This fixes "TypeError: undefined is not a function" when calling
updateStartupScript.

Also return a stack trace in the Luna payload on error to aid in
debugging any future issues.